# Generated by Django 3.2 on 2022-04-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_editors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editors',
        ),
    ]
