# Generated by Django 3.2 on 2022-04-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_delete_editors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('Happy', 'Happy'), ('Cinematic', 'Cinematic'), ('Games', 'Games'), ('Calm', 'Calm'), ('Vlog', 'Vlog')], default='Happy', max_length=20)),
                ('song_img', models.FileField(upload_to='')),
                ('artist', models.CharField(max_length=200)),
                ('song_file', models.FileField(upload_to='')),
            ],
        ),
    ]
