# Generated by Django 3.2 on 2022-04-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='genre',
            new_name='category',
        ),
    ]
