# Generated by Django 3.2 on 2022-04-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_genre_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='genre_img',
            new_name='category_img',
        ),
    ]
