# Generated by Django 3.2 on 2022-04-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20220414_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('happy', 'happy'), ('cinematic', 'cinematic'), ('games', 'games'), ('calm', 'calm'), ('vlog', 'vlog')], default='happy', max_length=20),
        ),
    ]
