# Generated by Django 3.2 on 2022-04-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='time_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
