# Generated by Django 3.2 on 2022-04-19 15:43

from django.db import migrations, models
import pages.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_song_time_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to='', validators=[pages.validators.validate_is_audio]),
        ),
    ]
