# Generated by Django 3.2 on 2022-04-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
