# Generated by Django 3.2 on 2022-04-29 08:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_song_favourites'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='song',
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
